version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - gocritic
    - govet
    - misspell
    - revive
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - exitAfterDefer
    govet:
      disable-all: false
    revive:
      rules:
        - name: blank-imports
          disabled: false
        - name: bool-literal-in-expr
          disabled: false
        - name: confusing-naming
          disabled: false
        - name: confusing-results
          disabled: false
        - name: constant-logical-expr
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: exported
          disabled: false
        - name: errorf
          disabled: false
        - name: if-return
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: modifies-value-receiver
          disabled: false
        - name: optimize-operands-order
          disabled: false
        - name: range-val-in-closure
          disabled: false
        - name: struct-tag
          disabled: false
        - name: superfluous-else
          disabled: false
        - name: time-equal
          disabled: false
        - name: unexported-naming
          disabled: false
        - name: unexported-return
          disabled: false
        - name: unnecessary-stmt
          disabled: false
        - name: unreachable-code
          disabled: false
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
