name: Lint & Test
on:
  pull_request:
  push:
    branches:
      - main

env:
  CGO_ENABLED: 1

jobs:
  test:
    uses: SiaFoundation/workflows/.github/workflows/go-test.yml@e57046123c35f2c64a91ec3e14fe3c9d2b0236a0 # master
