name: Add issues and PRs to Sia project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    uses: SiaFoundation/workflows/.github/workflows/project-add.yml@e57046123c35f2c64a91ec3e14fe3c9d2b0236a0 # master
    secrets: inherit
